export PRIVATE_KEY=$(cat <<EOF
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIGAczzQu77znu1BJnC0JdIGlH1ye8WhiVulIRJKE7nmeoAoGCCqGSM49
AwEHoUQDQgAEBUGRpkcG1oUlrxqsMLo9/Ga1epM66EueNTuZJ84pIDBq5hoVAwhs
+LWdrQgTRj+x9KNIYn4N77DGIjG6S8a+Gw==
-----END EC PRIVATE KEY-----
EOF
)
export PUBLIC_KEY=$(cat <<EOF
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEBUGRpkcG1oUlrxqsMLo9/Ga1epM6
6EueNTuZJ84pIDBq5hoVAwhs+LWdrQgTRj+x9KNIYn4N77DGIjG6S8a+Gw==
-----END PUBLIC KEY-----
EOF
)
export SERVER_PORT=8083
export DB_NAME=registrations_db
export GRPC_CLIENT_PORT=9091
export ENV=local
