services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=authdb
    ports:
      - "5432:5432"
    restart: always
  
  auth-service:
    container_name: auth-service
    image: evgeniyfimushkin/auth-service
    build: ./auth-service
    environment:
      - DB_HOST=db
      - PRIVATE_KEY=LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdBY3p6UXU3N3pudTFCSm5DMEpkSUdsSDF5ZThXaGlWdWxJUkpLRTdubWVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFQlVHUnBrY0cxb1Vscnhxc01MbzkvR2ExZXBNNjZFdWVOVHVaSjg0cElEQnE1aG9WQXdocworTFdkclFnVFJqK3g5S05JWW40Tjc3REdJakc2UzhhK0d3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
      - PUBLIC_KEY=LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdBY3p6UXU3N3pudTFCSm5DMEpkSUdsSDF5ZThXaGlWdWxJUkpLRTdubWVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFQlVHUnBrY0cxb1Vscnhxc01MbzkvR2ExZXBNNjZFdWVOVHVaSjg0cElEQnE1aG9WQXdocworTFdkclFnVFJqK3g5S05JWW40Tjc3REdJakc2UzhhK0d3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    ports:
      - "8080:8080"
    restart: always
