global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'auth-service'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['auth-service:9100']
 
  - job_name: 'event-service'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['event-service:9100']

  - job_name: 'registration-service'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['registration-service:9100'] 

  - job_name: 'nginx'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nginx-exporter:9113']

