global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']



  - job_name: 'auth-service'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['auth-service:9100']
