server {
    listen 80;
    server_name localhost;
    return 307 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/certificate.key;
    
    location /api/v1/auth/ { 
        proxy_pass http://auth-service:8081/api/v1/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/v1/events { 
        #auth_jwt_enabled on;
        #auth_jwt_algorithm 'ES256';
        #auth_jwt_location 'COOKIE=access_token';
        ##auth_jwt_redirect on;
        ##auth_jwt_loginurl 'http://localhost:/api/v1/auth/refresh';
        #auth_jwt_use_keyfile on;
        #auth_jwt_keyfile_path "/etc/nginx/jwt_public_key.pem";

        proxy_cache events_cache;
        proxy_cache_valid 200 1m;
        proxy_cache_bypass $request_method;

        proxy_pass http://event-service:8082/api/v1/events;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/v1/registrations { 
        #auth_jwt_enabled on;
        #auth_jwt_algorithm 'ES256';
        #auth_jwt_location 'COOKIE=access_token';
        ##auth_jwt_redirect on;
        ##auth_jwt_loginurl 'http://localhost:/api/v1/auth/refresh';
        #auth_jwt_use_keyfile on;
        #auth_jwt_keyfile_path "/etc/nginx/jwt_public_key.pem";


        proxy_pass http://registration-service:8083/api/v1/registrations;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
   
    location / {
        proxy_pass http://frontend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /nginx_status {
        stub_status;
        allow all;
    }
}

server {
    listen 443 ssl;
    server_name grafana.events-planner.ru;

    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/certificate.key;
    
    access_log off; 
    error_log /dev/null crit; 

    location / {
        proxy_pass http://grafana:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}


