name: build and push auth-service

on:
  push:
    branches:
      - backend

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build docker image
        run: |
          docker build -t evgeniyfimushkin/auth-service:latest services/auth-service

      - name: Log in to Porn Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push docker image
        run: docker push evgeniyfimushkin/auth-service:latest
