name: build and push auth-service

on:
  push:
    branches:
      - backend

jobs:
#  publish:
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        service:
#          - auth-service
#          - event-service
#          - registration-service
#
#    steps:
#      - name: checkout repository
#        uses: actions/checkout@v2
#
#      - name: Build docker image for ${{ matrix.service }}
#        run: |
#          docker build -t evgeniyfimushkin/${{ matrix.service }}:latest services/${{ matrix.service }}
#
#      - name: Log in to DockerHub
#        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#
#      - name: Push docker image for ${{ matrix.service }}
#        run: docker push evgeniyfimushkin/${{ matrix.service }}:latest
  deploy:
    #needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        scp -i <(${{ secrets.SSH_PRIVATE_KEY }}) ./services/docker-compose.yaml ${{ REMOTE_USER }}@${{ REMOTE_HOST }}:docker-compose.yaml
          chmod 600 ~/.ssh/id_rsa
